# Generated by Django 3.1.3 on 2020-12-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_title2'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='inder2',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
