# Generated by Django 3.1.3 on 2020-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_home_inder3'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='title4',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
