# Generated by Django 3.1.3 on 2020-12-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_home_title4'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='inder4',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
